#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const scriptPath = path.join(root, 'collector/windows/Collect-ElistlyDevice.ps1');
const launcherName = 'Start Elistly Device Collector.bat';
const launcherPath = path.join(root, 'collector/windows', launcherName);
const readmePath = path.join(root, 'collector/windows/README.txt');
const candidatePath = path.join(root, 'collector/windows/CANDIDATE.md');
const packageScriptPath = path.join(root, 'scripts/package-windows-collector.sh');
const appPath = path.join(root, 'app.js');
const appHtmlPath = path.join(root, 'app.html');
const serviceWorkerPath = path.join(root, 'sw.js');
const script = fs.readFileSync(scriptPath, 'utf8');
const launcher = fs.readFileSync(launcherPath, 'utf8');
const readme = fs.readFileSync(readmePath, 'utf8');
const candidate = fs.readFileSync(candidatePath, 'utf8');
const packageScript = fs.readFileSync(packageScriptPath, 'utf8');
const app = fs.readFileSync(appPath, 'utf8');
const appHtml = fs.readFileSync(appHtmlPath, 'utf8');
const serviceWorker = fs.readFileSync(serviceWorkerPath, 'utf8');

assert.match(script, /SaveFileDialog/, 'user must choose the report path');
assert.match(script, /elistly\.device-intake\.v1/);
assert.match(script, /networkDirectoryLookup\s*=\s*\$false/);
assert.match(script, /Get-CimInstance/);
assert.doesNotMatch(script, /-ExecutionPolicy|Bypass|Hidden|Set-Clipboard|clip\.exe|Get-AD|Invoke-WebRequest|Invoke-RestMethod|Net\.WebClient|TEMP|TMP/i);
assert.doesNotMatch(script, /product\s*key|password|token|wifi|browser|document/i);
assert.match(script, /ConvertTo-Json/);
assert.match(script, /WriteAllText\([^,]+,[^,]+,\s*\(New-Object System\.Text\.UTF8Encoding\(\$false\)\)\)/);
assert.match(readme, /standard.*non-administrator/i);
assert.match(readme, /does not.*network/i);
assert.match(readme, /PowerShell execution policy/i);
assert.match(readme, /delete.*report/i);
assert.match(readme, /Windows 10.*Windows 11/i);
assert.match(launcher, /%~dp0Collect-ElistlyDevice\.ps1/i, 'launcher must resolve the collector beside itself');
assert.match(launcher, /%SystemRoot%\\System32\\WindowsPowerShell\\v1\.0\\powershell\.exe.*-NoProfile.*-ExecutionPolicy Bypass.*-File/i, 'launcher must use trusted Windows PowerShell and bypass policy only for its child process');
assert.match(launcher, /choice\s+\/C\s+YN/i, 'launcher must ask before using the process-only bypass');
assert.match(launcher, /exit\s+\/b\s+%collector_exit%/i, 'launcher must preserve the collector result');
assert.doesNotMatch(launcher, /Set-ExecutionPolicy/i, 'launcher must not modify machine or user policy');
assert.match(readme, new RegExp(launcherName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'));
assert.match(readme, /only.*collector.*process|collector.*process.*only/i);
assert.match(readme, /does not change.*machine.*user.*policy/i);
assert.match(packageScript, /build-windows-shortcut\.js/);
assert.match(packageScript, /Elistly Device Collector\.lnk/);
assert.match(packageScript, /bin\/Elistly\.ico/);
assert.match(app, /Double-click.*Elistly Device Collector.*shortcut/i, 'in-app instructions must name the branded shortcut');
assert.doesNotMatch(app, /right-click Collect-ElistlyDevice\.ps1/i, 'in-app instructions must not direct users to the policy-blocked path');
assert.match(readme, /shortcut.*fallback|fallback.*shortcut/i);
assert.match(appHtml, /app\.js\?v=18/, 'app shell must request the shortcut-aware app bundle');
assert.match(serviceWorker, /elistly-shell-v8/);
assert.match(serviceWorker, /app\.js\?v=18/);
for (const [name, content] of [['README', readme], ['candidate metadata', candidate], ['package script', packageScript], ['app download', app]]) {
  assert.match(content, /Elistly-Windows-Device-Intake-v1\.0\.2|Collector 1\.0\.2/i, `${name} must reference collector 1.0.2`);
}
console.log('PASS windows-collector');
