/**
 * Writes config.js from environment variables (for Cloudflare Pages or CI).
 * Env vars: SUPABASE_URL, SUPABASE_ANON_KEY, ELISTLY_API_URL (optional).
 * Output: config.js in project root with the same names (window.SUPABASE_URL, etc.).
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';
const apiUrl = process.env.ELISTLY_API_URL || '';

const content = `/**
 * Elistly config – generated by scripts/write-config.js from env. Do not commit if it contains real keys.
 * Env vars used: SUPABASE_URL, SUPABASE_ANON_KEY, ELISTLY_API_URL
 */
(function () {
  'use strict';
  window.SUPABASE_URL = ${JSON.stringify(url)};
  window.SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};
  window.ELISTLY_API_URL = ${JSON.stringify(apiUrl)};
})();
`;

fs.writeFileSync(path.join(root, 'config.js'), content, 'utf8');
console.log('Wrote config.js from env (SUPABASE_URL, SUPABASE_ANON_KEY, ELISTLY_API_URL).');