/**
 * Writes config.js from environment variables (for Cloudflare Pages or CI).
 * Set SUPABASE_URL and SUPABASE_ANON_KEY in the build environment.
 * Output: config.js in project root (so the deployed site has the keys at build time).
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';
const apiUrl = process.env.ELISTLY_API_URL || '';

const content = `/**
 * Elistly config – generated by scripts/write-config.js from env. Do not commit if it contains real keys.
 */
(function () {
  'use strict';
  window.ELISTLY_CONFIG = {
    supabaseUrl: ${JSON.stringify(url)},
    supabaseAnonKey: ${JSON.stringify(anonKey)},
    apiUrl: ${JSON.stringify(apiUrl)}
  };
})();
`;

fs.writeFileSync(path.join(root, 'config.js'), content, 'utf8');
console.log('Wrote config.js from env (SUPABASE_URL, SUPABASE_ANON_KEY, optional ELISTLY_API_URL).');
