/**
 * Writes config.js from environment variables (for Cloudflare Pages or CI).
 * Preferred env vars: ELISTLY_API_URL, NEON_AUTH_URL.
 * Output: config.js in project root. Do not expose database or auth secrets here.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const apiUrl = process.env.ELISTLY_API_URL || '';
const neonAuthUrl = process.env.NEON_AUTH_URL || '';

const content = `/**
 * Elistly config – generated by scripts/write-config.js from env. Do not commit if it contains real keys.
 * Env vars used: ELISTLY_API_URL, NEON_AUTH_URL
 */
(function () {
  'use strict';
  window.ELISTLY_API_URL = ${JSON.stringify(apiUrl)};
  window.NEON_AUTH_URL = ${JSON.stringify(neonAuthUrl)};
})();
`;

fs.writeFileSync(path.join(root, 'config.js'), content, 'utf8');
console.log('Wrote config.js from env (ELISTLY_API_URL, NEON_AUTH_URL).');
